# XXX See https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# Deploy to Vercel when anything is pushed in the "master" branch.
# You must have added a GitHub secret "ZEIT_TOKEN" in your GitHub project for the deploy to succeed
name: Deploy to Now production

on:
  push:
    branches:
      - 'master'

jobs:
  setup:
    name: Setup deployment environment
    runs-on: ubuntu-latest
    steps:
      - name: Installing node.js
        uses: actions/setup-node@v1 # Used to install node environment
        with:
          node-version: '10.x' # Use the same node.js version as the one Vercel's uses (currently node14.x)

  deploy-production:
    name: Deploy on production
    runs-on: ubuntu-latest
    needs: setup # Need to wait for setup
    steps:
      - uses: actions/checkout@v1 # Get last commit pushed
      - name: Deploying on Vercel
        run: yarn deploy:production --token $ZEIT_TOKEN
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }} # Passing github's secret to the worker
